name: Go

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"

      - name: Build
        run: go build -v ./...

      - name: Tests
        run: go test -v ./...

  system-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.3"

      - name: System Tests
        run: go test -tags system_test -v ./...
